# PERL LOOPS 
# PERL WHILE LOOP 
# 
# 

#!/usr/local/bin/perl
 
$a = 10;

# while loop execution
while( $a < 20 ) {
   printf "Value of a: $a\n";
   $a = $a + 1;
}



# PERL LOOPS 
# PERL UNTIL LOOP 
#
#

#!/usr/local/bin/perl 
$a = 5; 
# until loop execution 
until( $a > 10 ) { 
  printf "Value of a: $a\n";                     
  $a = $a + 1; 
} 

# for loop 

#!/usr/local/bin/perl
 
# for loop execution
for( $a = 10; $a < 20; $a = $a + 1 ) {
   print "value of a: $a\n";
}
